### PR TITLE
Feature configuration abstraction

### PR DESCRIPTION
**Pull request by arocnies**
# Build and Scans

Branch Build Status: [Build Status](https://jenkins.ossim.io/job/omar-volume-cleanup/job/feature-configuration-abstraction/)

Branch Jenkins Pipeline: https://jenkins.ossim.io/job/omar-volume-cleanup/job/feature-configuration-abstraction/

Branch SonarQube: https://sonarcloud.io/project/issues?branch=feature-configuration-abstraction&id=ossimlabs_omar-volume-cleanup&resolved=false

# Overview
### Configuration decoupled from main app
This PR separates decouples the configuration from the application itself. This means the config library, "Konf", is not coupled to the app and can be replaced and managed in one place. This would be important if we needed to switch to another library or config process (i.e. #6).

### Tests for configuration
Tests to have been added to make sure environment variables are picked up by the Configuration logic.

### Jenkins multibranch pipeline succeeds on first load
In addition to the configuration changes, I've modified the Jenkinsfile to use `get[]` syntax for selecting the build node. This fixes the issue of when a new feature branch is first detected by Jenkins, it would fail. I included this change in the PR since it's so small. It's been tested on Jenkins and behaves as expected. Although I understand if we want ot 

# Change Details:
> Added `Configuration` singleton that is responsible for providing configuration values.
> Replaced direct use of Konf in `App.kt` and the main method with the new `Configuration` object.
> Fixed DRYRUN misspelling environment variable in both the docker and config logic.
> Konf configuration specs are now private to `Configuration`
> Added tests to confirm Configuration is loads environment variables.

### CODE REVIEW

**Comment by arocnies** [comment]
Some newer changes summed up:

The `Configuration` singleton has been turned into a normal class--which is preferred as singletons restrict design more than we want in this case.
Tests now include cases for 0%, 1%, 99%, and 100% (as well as the initial test of %50)

**Review by Spectrality — APPROVED** [review]
Very clean overall, I'd love to see it in action. I will clone and run the tests locally. Really cool stuff! As someone who doesn't know much Kotlin, I still found it relatively easy to read and understand what was going on. Lots of function chaining, that's for sure.

**Comment by melbsurfer** [comment]
I think this looks good.  I like the tests, and think they do a good job covering the scenarios; however, I think it is time to wire it up, and give it a try on Openshift DEV.

**Review by melbsurfer — APPROVED** [review]
See previous comment.

**Comment by arocnies** [comment]
Thanks for the reviews @Spectrality and @melbsurfer!

It's definitely time to drop this into our deployment and see it integrated into a running system.
I plan to use the remaining DR hours to do the dev deployment--I'll let you know when it's up.

**Pull request merged**
